#!/bin/bash
# $NODE_NAME install.sh — root-only, plug-and-play new-VPS installer.
#
# Prompts for what it cannot detect (domain, Cloudflare API token, Tailscale
# auth key), one explicit `true`/`false` per module, and — LAST, opt-in — remote
# access to the operator's own GitHub repos. Then it runs unattended: host
# services, docker, tailscale, the full
# stack — Nextcloud (app + PostgreSQL + Redis + Talk HPB/TURN), Caddy,
# Vaultwarden, Uptime Kuma, Docker Mailserver + Roundcube —
# Cloudflare DNS records, and LE cert issuance. The repo already carries
# the canonical <domain> naming (modules/<domain>/, vhosts/<host>.caddy);
# no legacy renames are applied.
#
# Fully autonomous: the Kuma admin account is created
# automatically (the admin passwords are printed once in the final summary —
# nothing is written to disk), and no manual confirmation steps block success —
# the only follow-ups are printed in the summary (Tailscale split-DNS, mailboxes).
# The one step that does wait is the opt-in GitHub remote access: the operator
# asked for it, so the installer holds until the key it minted is authorized.
# Prerequisites checked up front: the Cloudflare zone must exist. The repo is
# PUBLIC and is cloned over HTTPS — the clone needs no GitHub key; the key the
# opt-in step mints is for PUSHING to the operator's own repos.
#
# Errors are collected with tags, each shown as a "problem" plus a separate
# "hint". Manual dashboard steps are grouped as expected; real failures as
# unexpected. No success message is printed until every error is resolved:
# after the setup you get a numbered list of what's still failing, and each
# time you press Enter the script re-checks them, prints the solved ones
# once, and the remaining ones — until all are green.
#
# Entry point: root@$NODE_NAME is the ONLY way in (key-only SSH over the
# tailnet). The installer runs entirely as root — no sudo user, no hand-off.
#
# Usage:
#   scp scripts/install/install.sh root@$NODE_NAME:
#   ssh root@$NODE_NAME
#   bash install.sh
#
# Paths: the repo lives at $REPO ($ROOT); every external,
# untracked artefact (data, modules, databases, uploads) lives under $DATA
# ($ROOT/data), which .gitignore excludes.

. "$(dirname "$(readlink -f "$0")")/../lib/instance.sh" 2>/dev/null || true

set -uo pipefail

# The checkout path is DERIVED from this script's location — never
# hardcoded — so the repo can live anywhere and be renamed
# ($NODE_NAME -> kefoServer) without editing any script.
REPO="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"
# Every other part of the repo (Makefile, scripts/*) calls the checkout root
# $ROOT; this installer is the one place that names it $REPO. Both must exist:
# the $ROOT/data paths below aborted the run under `set -u`.
ROOT="$REPO"
DATA="$REPO/data"

# GITHUB_USER owns the repos. instance.conf wins (scripts/lib/instance.sh loaded
# it above); otherwise the checkout's own origin remote is the truth. The
# lib's placeholder fallback must never stand in for it — an install that used
# it wrote GITHUB_USER= into instance.conf (leaving {{GITHUB_USER}} unresolved in
# the rendered vhosts/logrotate rule) AND rewrote origin to
# https://github.com/exampleuser/$REPO_NAME.git, clobbering the real remote.
if [ -z "${GITHUB_USER:-}" ] || [ "$GITHUB_USER" = "exampleuser" ]; then
  _owner="$(git -C "$REPO" remote get-url origin 2>/dev/null \
            | sed -nE 's#^(git@github\.com:|https?://github\.com/)([^/]+)/.*#\2#p')"
  [ -n "$_owner" ] && GITHUB_USER="$_owner"
  unset _owner
fi

# Canonical node name for this project: the repo is kefoServer, the tailnet node
# and the sole login are root@kefoserver. The installer owns this decision — it
# sets the static hostname to match (phase_host) and writes HOSTNAME=$NODE_NAME
# into data/instance.conf, so every other script derives the name from there
# rather than hardcoding it.
NODE_NAME=kefoserver
RENDER_DIR="$DATA/rendered"
# NC recovery manifests live OUTSIDE the repo tree ($DATA/cloud/recovery —
# instance state generated by `make nc-capture`; gitignored via /data/).
MANIFEST_DIR="$DATA/cloud/recovery"
# Instance state and logs live under ONE '$GITHUB_USER' namespace, outside the
# repo: $STATE_DIR (state — it holds the CF token + Tailscale key, so
# it stays root-only 0700, never a world-writable sticky dir like /var/tmp) and
# $LOG_DIR (EVERY log this project writes: install, uninstall and any
# module log). One place to look, one logrotate rule to bound it, no per-repo
# log dir and no chronicle-style per-event logging.
STATE_DIR=$STATE_DIR
LOG_DIR=$LOG_DIR
STATE="$STATE_DIR/setup.state"
LOG="$LOG_DIR/install.log"
ERR_TAGS=()
declare -A ERR_DETAIL=()

log()  { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG"; }
fail() {
  local t
  for t in "${ERR_TAGS[@]}"; do [ "$t" = "$1" ] && return 0; done  # no duplicates across runs
  ERR_TAGS+=("$1"); ERR_DETAIL[$1]="${2:-}"
  echo "  ERROR: $(problem "$1")${2:+ ($2)}" >>"$LOG"
}

banner() {
cat <<'EOF'
██╗  ██╗ ██████╗ ███╗   ███╗███████╗██╗      █████╗ ██████╗
██║  ██║██╔═══██╗████╗ ████║██╔════╝██║     ██╔══██╗██╔══██╗
███████║██║   ██║██╔████╔██║█████╗  ██║     ███████║██████╔╝
██╔══██║██║   ██║██║╚██╔╝██║██╔══╝  ██║     ██╔══██║██╔══██╗
██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗███████╗██║  ██║██████╔╝
╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝╚═════╝

  One-shot setup for a fresh Debian VPS: Nextcloud (app + PostgreSQL +
  Redis + Talk HPB/TURN), Caddy, Vaultwarden, Uptime Kuma
  and the Docker Mailserver + Roundcube platform (named after your
  domain) behind Cloudflare, with tailscale, ttyd, dnsmasq and goose
  as host services. Prompts once (domain, Cloudflare API token,
  Tailscale auth key), then runs unattended — errors are listed with
  a hint each and re-checked until resolved, and success prints only
  when all are green.

WARNING: SSH (port 22) is tailnet-only — your current session stays alive, but the next login must come from a Tailscale device.
EOF
}

load_state() {
  [ -f "$STATE" ] && . "$STATE"
  local uniq=() t
  for t in "${ERR_TAGS[@]:-}"; do
    [[ " ${uniq[*]:-} " == *" $t "* ]] || uniq+=("$t")
  done
  ERR_TAGS=("${uniq[@]}")
}

save_state() {
  umask 077
  install -d -m 0700 "$(dirname "$STATE")"
  local tmp="$STATE.tmp.$$"
  cat > "$tmp" <<EOF
DOMAIN='$DOMAIN'
CF_API_TOKEN='$CF_API_TOKEN'
TS_AUTHKEY='$TS_AUTHKEY'
TS_IP='${TS_IP:-}'
MOD_CLOUD='${MOD_CLOUD:-true}'
MOD_VAULT='${MOD_VAULT:-true}'
MOD_MAIL='${MOD_MAIL:-true}'
MOD_MONITOR='${MOD_MONITOR:-true}'
ERR_TAGS=($(printf '%q ' "${ERR_TAGS[@]}"))
EOF
  chmod 600 "$tmp"
  mv -f "$tmp" "$STATE" 2>/dev/null || sudo mv -f "$tmp" "$STATE" || rm -f "$tmp"
  chown root:root "$STATE" 2>/dev/null || true
}

# $LOG and $STATE live outside the repo and must exist before ANYTHING redirects
# into them (a `>>"$LOG"` whose directory is missing fails the redirection, the
# command behind it is never run, and `|| fail ...` then reports the step as
# broken) — and before the first `log()`, or tee swallows that line. Idempotent;
# main() calls it first thing.
ensure_runtime_dirs() {
  install -d -m 0755 "$LOG_DIR"
  install -d -m 0700 "$STATE_DIR"
}

# Module prompts are ALWAYS asked — there is no answer-sheet defaults file any
# more. A pre-filled default is exactly how a stale value (e.g. DOMAIN left over
# from a previous run) silently skipped a prompt the operator needed to see.
# Every boolean prompt takes an EXPLICIT true or false: no Enter-accepts-default,
# and never a default of true — a pre-selected answer is how a stale choice
# survives a re-run. Anything else re-asks.
ask_boolean() {   # ask_boolean <question> <variable>
  local q="$1" var="$2" answer
  while :; do
    read -rp "$q (true/false): " answer || return 1
    case "${answer,,}" in
      true)  printf -v "$var" '%s' true;  return 0 ;;
      false) printf -v "$var" '%s' false; return 0 ;;
      *)     echo "   type true or false." ;;
    esac
  done
}

ask_modules() {
  local k var
  for k in cloud vault mail monitor; do
    var="MOD_${k^^}"
    [ -n "${!var:-}" ] && continue        # already answered (resume)
    ask_boolean "Set up the $k module?" "$var" || exit 1
  done
}

# ── SSH access: STRICT and required ──────────────────────────────────────
# The box ends up root-key-only with password auth off, so a usable pubkey from
# a device the operator actually holds is REQUIRED — the installer asks for it
# here instead of leaving it as a follow-up `ssh_keys` step. Only the PUBLIC
# half is pasted; the private half never leaves that device. Nothing is ever
# minted server-side (that is the difference to the opt-in GitHub key below).
ask_ssh_key() {
  local line info
  mkdir -p /root/.ssh && chmod 700 /root/.ssh
  if [ -s /root/.ssh/authorized_keys ] && grep -q . /root/.ssh/authorized_keys; then
    log "  SSH: $(grep -c . /root/.ssh/authorized_keys) key(s) already authorized — paste skipped"
    return 0
  fi
  printf '\n SSH is key-only (root, no password). On the device you will connect FROM run\n'
  printf '   cat ~/.ssh/id_ed25519.pub\n'
  printf ' and paste that one line here (no ssh-copy-id needs to run yet). Only the\n'
  printf ' PUBLIC half goes to the server; the private half never leaves your device.\n'
  printf ' Use a key you can actually use — hardening is key-only, so a wrong or lost\n'
  printf ' key is a lockout.\n\n'
  while :; do
    read -rp "Public SSH key of your device: " line \
      || { echo "A public key is required — re-run the installer from a terminal."; exit 1; }
    line="$(printf '%s' "$line" | tr -d '\r' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    case "$line" in
      "") continue ;;
      *"PRIVATE KEY"*) echo "   that is the PRIVATE key — never paste it; paste the .pub line."; continue ;;
    esac
    info="$(printf '%s\n' "$line" | ssh-keygen -lf - 2>/dev/null)"
    [ -n "$info" ] || { echo "   not a valid public key — paste the whole .pub line (ssh-ed25519 AAAA… you@device)."; continue; }
    grep -qxF "$line" /root/.ssh/authorized_keys 2>/dev/null \
      || printf '%s\n' "$line" >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    log "  SSH key accepted: $info"
    return 0
  done
}

ask_inputs() {
  if [ -z "${DOMAIN:-}" ]; then
    read -rp "Domain (e.g. example.com): " DOMAIN
  fi
  DOMAIN="${DOMAIN,,}"
  [[ "$DOMAIN" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]] || { echo "Invalid domain: $DOMAIN"; exit 1; }
  if [ -z "${CF_API_TOKEN:-}" ]; then
    read -rsp "Cloudflare API token (Zone > DNS > Edit): " CF_API_TOKEN; echo
  fi
  [ -n "$CF_API_TOKEN" ] || { echo "Token required."; exit 1; }
  if [ -z "${TS_AUTHKEY:-}" ]; then
    read -rsp "Tailscale auth key (tskey-...): " TS_AUTHKEY; echo
  fi
  [ -n "$TS_AUTHKEY" ] || { echo "Auth key required."; exit 1; }
  ask_modules
  # STRICT: key-only SSH means a usable pubkey is required, asked BEFORE the
  # GitHub question below (that one is opt-in).
  ask_ssh_key
  # LAST prompt, opt-in, explicit true/false: mint a GitHub key for pushing to
  # the operator's OWN repos, print it, wait until it is authorized, push.
  [ -n "${GH_REMOTE:-}" ] || ask_boolean "Configure remote access to your own GitHub account's repositories?" GH_REMOTE || exit 1
  echo "Installing for $DOMAIN — ~10-15 min. Full log: $LOG"
}

# Module detection, cross-checked. Written at the END of a successful install
# and refreshed on every re-run. Three artefacts, all under $DATA (gitignored):
#   installed-modules.conf           declared modules (the install-time choice)
#   installed-modules.detected.conf  modules confirmed by independent probes
#   installed-modules.report.txt     per-module, per-method evidence matrix
# Probes, deliberately independent of the declared choice: (1) the container
# is running, (2) its compose file exists in the repo, (3) its data dir/db
# exists on disk, (4) its Caddy vhost exists. A module is "confirmed" when at
# least one probe fires; a declared/confirmed mismatch is logged as a warning.
# Consumed by scripts/stack/smoke-vhosts.sh + scripts/info/fetch.sh.
write_modules_conf() {
  local conf="$DATA/installed-modules.conf"
  local det="$DATA/installed-modules.detected.conf"
  local rep="$DATA/installed-modules.report.txt"
  local m ct cf dd vh ev

  : > "$conf"; : > "$det"
  { echo "module detection report — $(date -Is)"
    echo "declared = install-time choice (MOD_*); probes are independent of it."
    echo; } > "$rep"

  for m in cloud vault mail monitor; do
    [ "${MOD_${m^^}:-true}" = "true" ] && echo "$m" >> "$conf"
  done

  for m in cloud vault mail monitor; do
    ct=0; cf=0; dd=0; vh=0
    case "$m" in
      cloud)   ct=$(docker ps --format '{{.Names}}' 2>/dev/null | grep -cx nextcloud)
               [ -f "$REPO/modules/nextcloud/docker-compose.yml" ] && cf=1
               [ -e "$DATA/cloud/users" ] && dd=1
               [ -f "$RENDER_DIR/caddy/vhosts/cloud.caddy" ] && vh=1 ;;
      vault)   ct=$(docker ps --format '{{.Names}}' 2>/dev/null | grep -cx vaultwarden)
               [ -f "$REPO/modules/vaultwarden/docker-compose.yml" ] && cf=1
               [ -e "$DATA/vault/data" ] && dd=1
               [ -f "$RENDER_DIR/caddy/vhosts/vault.caddy" ] && vh=1 ;;
      mail)    ct=$(docker ps --format '{{.Names}}' 2>/dev/null | grep -cxE 'mailserver|roundcube')
               [ -f "$REPO/modules/mailserver/docker-compose.yml" ] && cf=1
               [ -e "$DATA/mailserver/data" ] && dd=1
               [ -f "$RENDER_DIR/caddy/vhosts/mail.caddy" ] && vh=1 ;;
      monitor) ct=$(docker ps --format '{{.Names}}' 2>/dev/null | grep -cx uptimekuma)
               [ -f "$REPO/modules/uptimekuma/docker-compose.yml" ] && cf=1
               [ -e "$DATA/kuma/data" ] && dd=1
               [ -f "$RENDER_DIR/caddy/vhosts/kuma.caddy" ] && vh=1 ;;
    esac
    ev=$((ct+cf+dd+vh))
    [ "$ev" -gt 0 ] && echo "$m" >> "$det"
    printf '%-8s declared=%s running=%s compose=%s data=%s vhost=%s -> %s\n' \
      "$m" "$([ "${MOD_${m^^}:-true}" = true ] && echo 1 || echo 0)" \
      "$ct" "$cf" "$dd" "$vh" "$([ "$ev" -gt 0 ] && echo PRESENT || echo absent)" >> "$rep"
  done

  log "  wrote $conf ($(paste -sd' ' "$conf"))"
  log "  detected: $(paste -sd' ' "$det" || echo none) — evidence: $rep"
  if ! diff -q <(sort "$conf") <(sort "$det") >/dev/null 2>&1; then
    log "  WARNING: declared modules != detected modules — see $rep"
  fi
}

# ───────────────── GitHub remote access (opt-in, last prompt) ─────────────

# The ONE keypair this installer mints: it has to exist on the box to push to
# the operator's repos. (The operator's own login key is never minted — it is
# pasted at the ask_ssh_key prompt.) The operator authorizes the printed PUBLIC
# key once.
GH_KEY=/root/.ssh/github_key

github_keygen() {
  [ -s "$GH_KEY" ] && return 0                      # never overwrite an existing key
  ssh-keygen -t ed25519 -N "" -C "$(id -un)@$(hostname -s) github_key" -f "$GH_KEY" >/dev/null 2>&1 || return 1
  chmod 600 "$GH_KEY"; chmod 644 "$GH_KEY.pub"
  # ssh does not offer this key by default: name it in the client config.
  grep -qs "IdentityFile $GH_KEY" /root/.ssh/config 2>/dev/null && return 0
  printf 'Host github.com\n  IdentityFile %s\n  IdentitiesOnly yes\n' "$GH_KEY" >> /root/.ssh/config
  chmod 600 /root/.ssh/config
}

# Pin github.com's host keys, but only ones whose fingerprint api.github.com
# publishes — a bare ssh-keyscan trusts whoever answered first.
github_known_hosts() {
  local scan fps published f n=0
  grep -qs 'github\.com' /root/.ssh/known_hosts 2>/dev/null && return 0
  scan="$(ssh-keyscan -t rsa,ecdsa,ed25519 github.com 2>/dev/null)" || return 0
  [ -n "$scan" ] || return 0
  fps="$(printf '%s\n' "$scan" | ssh-keygen -lf - 2>/dev/null | awk '{print $2}')"
  published="$(curl -fsS --max-time 10 https://api.github.com/meta 2>/dev/null \
    | python3 -c 'import json,sys; print("\n".join(json.load(sys.stdin)["ssh_key_fingerprints"].values()))' 2>/dev/null)"
  for f in $fps; do
    n=$((n+1))
    printf '%s\n' "$published" | grep -qxF "$f" || return 0   # unverified — leave it to ssh
  done
  [ "$n" -gt 0 ] && printf '%s\n' "$scan" >> /root/.ssh/known_hosts && chmod 600 /root/.ssh/known_hosts
}

# GitHub answers a successful key test with exit 1 and a "successfully
# authenticated" line, so the MESSAGE is the test, not the exit code — and the
# output has to be captured first: under `set -o pipefail` a `ssh … | grep -q`
# reports ssh's 1 even when grep matched.
github_auth_ok() {
  local out
  [ -s "$GH_KEY" ] || return 1
  out="$(ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -T git@github.com 2>&1)" || true
  printf '%s' "$out" | grep -q "successfully authenticated"
}

github_push() {
  git -C "$REPO" remote set-url origin "git@github.com:$GITHUB_USER/$REPO_NAME.git" 2>/dev/null || true
  # SKIP_SMOKE: the pre-push hook's live vhost test cannot pass this early — the
  # stack is not up yet, and what is pushed here is the repo's content.
  SKIP_SMOKE=1 git -C "$REPO" push >>"$LOG" 2>&1 || return 1
}

github_access() {
  [ "${GH_REMOTE:-false}" = "true" ] || { log "  GitHub remote access: not requested — skipped"; return 0; }
  github_keygen || { fail github_key; return; }
  github_known_hosts
  if ! github_auth_ok; then
    printf '\n ── GitHub key — authorize it once, then the installer continues ───────\n'
    printf '   GitHub → Settings → SSH and GPG keys → New SSH key → paste this line:\n\n'
    printf '   %s\n\n' "$(cat "$GH_KEY.pub")"
    printf '   (Settings is under the avatar menu, top right; "New SSH key" is the\n'
    printf '    green button in the SSH keys box — name it after this host.)\n'
    printf ' ───────────────────────────────────────────────────────────────────────\n\n'
    # Strict: the operator asked for this feature, so there is no skip — the
    # loop only ends when GitHub accepts the key (Ctrl-C aborts the installer).
    until github_auth_ok; do
      read -rp "Add the key at GitHub, then press Enter to test again (Ctrl-C aborts): " _ \
        || { fail github_auth "no terminal to wait on — authorize $GH_KEY.pub by hand"; return; }
      echo "   not authorized yet — the whole line above goes into your GitHub ACCOUNT."
    done
  fi
  log "  GitHub key authorized (ssh -T git@github.com)"
  if [ -z "${GITHUB_USER:-}" ] || [ "$GITHUB_USER" = "exampleuser" ]; then
    fail github_auth "cannot tell which account to push to — no origin remote and no GITHUB_USER in $DATA/instance.conf"
    return
  fi
  github_push || fail github_auth "push failed — see $LOG"
}

# ───────────────────────────── Phase 1 (root) ─────────────────────────────

phase_host() {
  log "Phase 1 (host): packages, ssh, docker, tailscale, firewall"
  # Log may contain host/secret-adjacent output — root-readable only, never 666.
  # One-time relocation off the pre-$GITHUB_USER paths (never drop the old log).
  if [ ! -f "$LOG" ]; then
    for old in /var/log/$NODE_NAME-install.log /var/log/homelab-install.log; do
      [ -f "$old" ] && { mv -f "$old" "$LOG"; break; }
    done
  fi
  if [ ! -f "$STATE" ] && [ -f /var/lib/$NODE_NAME/setup.state ]; then
    mv -f /var/lib/$NODE_NAME/setup.state "$STATE"
  fi
  touch "$LOG" && chmod 640 "$LOG"

  # Canonical machine name: the repo, the tailnet node and root@$NODE_NAME must
  # all be 'kefoserver'. Set the static hostname so they agree even on a provider
  # image whose hostname is a throwaway (vps-xxxxxxxx).
  if [ "$(hostname -s 2>/dev/null)" != "$NODE_NAME" ]; then
    hostnamectl set-hostname "$NODE_NAME" >>"$LOG" 2>&1 || true
    log "  hostname set to $NODE_NAME (tailnet node will be $NODE_NAME)"
  fi

  DEBIAN_FRONTEND=noninteractive apt-get update -qq >>"$LOG" 2>&1
  # bzip2 is REQUIRED: goose's official download_cli.sh ships a .tar.bz2 — without
  # bzip2 the extraction fails and goose lands in the error list as a phantom
  # "unexpected error" whose real cause is a missing extractor.
  # dnsutils = dig: the dkim_setup re-check and its hint query the zone's
  # nameserver directly ("dig +short TXT mail._domainkey.$DOMAIN @<zone NS>"),
  # so without it that re-check could never pass and the installer looped on a
  # dkim tag whose only fault was a missing tool (2026-09-25).
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    git curl make sudo dnsmasq ufw jq apache2-utils fail2ban sqlite3 python3-yaml tmux bzip2 dnsutils >>"$LOG" 2>&1 || fail apt
  # Docker: Debian packages first (bookworm ships docker-compose-plugin).
  # trixie does not, so fall back to Docker's official repo (docker-ce).
  if ! DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker.io docker-compose-plugin >>"$LOG" 2>&1; then
    log "  docker-compose-plugin not in distro — installing docker-ce from Docker's repo"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ca-certificates curl gnupg >>"$LOG" 2>&1
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg 2>>"$LOG"
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      > /etc/apt/sources.list.d/docker.list
    DEBIAN_FRONTEND=noninteractive apt-get update -qq >>"$LOG" 2>&1
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >>"$LOG" 2>&1 || fail apt
  fi
  command -v docker >/dev/null 2>&1 || fail apt

  # Single operator account: root. The provider image may ship a login-capable
  # account (e.g. the cloud-init 'debian' user) — remove every non-root account
  # with a real UID so root@$NODE_NAME is genuinely the only way in.
  local u uid home
  while IFS=: read -r u _ uid _ _ home _; do
    [ "$u" = root ] && continue
    [ "$uid" -ge 1000 ] 2>/dev/null || continue
    [ "$uid" -lt 65534 ] || continue
    log "  removing non-root login account '$u' ($home)"
    pkill -u "$u" 2>/dev/null || true
    sleep 1
    userdel -r "$u" >>"$LOG" 2>&1 || userdel "$u" >>"$LOG" 2>&1 || true
  done < <(getent passwd)

  # SSH: root key-only. The operator's pubkey is collected by ask_ssh_key BEFORE
  # this phase (strict), so a missing key here means the step failed — the
  # `ssh_keys` guard stays as the safety net, and hardening (password auth off,
  # root key-only) is applied ONLY once a usable key exists, so the box is never
  # locked out. The installer never mints a server-side login keypair.
  mkdir -p /root/.ssh
  chmod 700 /root/.ssh
  if [ -s /root/.ssh/authorized_keys ]; then
    chmod 600 /root/.ssh/authorized_keys
    printf 'PasswordAuthentication no\nPermitRootLogin prohibit-password\nAllowUsers root\n' \
      > /etc/ssh/sshd_config.d/50-cloud-init.conf
    chmod 600 /etc/ssh/sshd_config.d/50-cloud-init.conf
    systemctl restart sshd
    log "  sshd hardened: key-only root login (AllowUsers root)"
  else
    fail ssh_keys
    log "no SSH key in /root/.ssh/authorized_keys (ask_ssh_key should have installed one) — add a pubkey, then re-check; sshd stays password-capable until then"
  fi

  systemctl enable --now docker >>"$LOG" 2>&1 || log "docker enable/start failed (re-checks will catch it)"
  mkdir -p /etc/docker
  # Write the daemon config only if it differs — never clobber a working one.
  cat > /etc/docker/daemon.json.new <<'EOF'
{
    "log-driver": "json-file",
    "log-opts": {"max-size": "10m", "max-file": "3"},
    "storage-driver": "overlay2",
    "default-runtime": "runc",
    "live-restore": true
}
EOF
  if ! diff -q /etc/docker/daemon.json /etc/docker/daemon.json.new >/dev/null 2>&1; then
    mv /etc/docker/daemon.json.new /etc/docker/daemon.json
    systemctl restart docker >>"$LOG" 2>&1 || log "docker restart failed (re-checks will catch it)"
  else
    rm -f /etc/docker/daemon.json.new
  fi
  if ! systemctl is-active --quiet docker; then
    systemctl start docker >>"$LOG" 2>&1 || log "docker start failed (re-checks will catch it)"
  fi

  if ! command -v goose >/dev/null 2>&1 && [ ! -x /usr/local/bin/goose ]; then
    # Official installer (release archive, .tar.bz2 — hence the bzip2 apt dep
    # above). Its output goes to the log, not /dev/null, so a failure is
    # diagnosable instead of surfacing as a bare "goose binary not installed".
    curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh \
      | CONFIGURE=false GOOSE_BIN_DIR=/usr/local/bin bash >>"$LOG" 2>&1 || true
  fi
  if command -v goose >/dev/null 2>&1; then
    install -m 0755 "$(command -v goose)" /usr/local/bin/goose || true
  elif [ -x "$HOME/.local/bin/goose" ]; then
    install -m 0755 "$HOME/.local/bin/goose" /usr/local/bin/goose || true
  fi
  command -v goose >/dev/null 2>&1 || [ -x /usr/local/bin/goose ] || fail goose

  if ! command -v tailscale >/dev/null 2>&1; then
    curl -fsSL https://tailscale.com/install.sh | sh || fail tailscale
  fi
  # Encrypt the tailscaled state file at rest (the console's tsStateEncrypted).
  # On Linux the flag NEEDS a TPM (/dev/tpmrm0): on a box without one, forcing
  # `--encrypt-state` makes tailscaled fail to start and takes the node offline,
  # so enable it only when the device exists — and start tailscaled fresh with
  # it before joining, so the state is encrypted from the first write.
  if [ -e /dev/tpmrm0 ] && [ -f /etc/default/tailscaled ]; then
    if ! grep -q -- '--encrypt-state' /etc/default/tailscaled; then
      sed -i -E 's|^FLAGS=.*|FLAGS="--encrypt-state"|' /etc/default/tailscaled
      systemctl restart tailscaled >>"$LOG" 2>&1 || log "tailscaled restart failed after enabling --encrypt-state"
      log "  tailscale state encryption enabled (FLAGS=--encrypt-state, TPM present)"
    fi
  elif [ ! -e /dev/tpmrm0 ]; then
    log "  no TPM (/dev/tpmrm0): tailscale state encryption unsupported here — left off"
  fi
  if ! tailscale ip -4 >/dev/null 2>&1; then
    # --hostname makes the tailnet node '$NODE_NAME', so the sole entry point
    # is root@$NODE_NAME (MagicDNS) regardless of the local machine hostname.
    tailscale up --authkey="$TS_AUTHKEY" --hostname=$NODE_NAME >>"$LOG" 2>&1 || fail tailscale_up
  fi
  TS_IP=$(tailscale ip -4 2>/dev/null | head -1)
  [ -n "$TS_IP" ] && log "tailscale IP: $TS_IP" || fail ts_ip

  ufw allow from 100.64.0.0/10 to any port 22 proto tcp >/dev/null 2>&1
  # Keep the current SSH client reachable even before it joins the tailnet, so
  # enabling ufw never locks the operator out mid-install. This is a TEMPORARY
  # rule for the installer session only: the IP is remembered and the rule is
  # deleted once the run succeeds (finalize_hardening) — a permanent rule for a
  # consumer/dynamic IP would be a standing hole.
  INSTALLER_SSH_IP="${SSH_CLIENT:+$(echo "$SSH_CLIENT" | awk '{print $1}')}"
  if [ -n "$INSTALLER_SSH_IP" ]; then
    ufw allow from "$INSTALLER_SSH_IP" to any port 22 proto tcp >/dev/null 2>&1 || true
  fi
  ufw allow 80/tcp >/dev/null 2>&1
  ufw allow 443/tcp >/dev/null 2>&1
  # Self-hosted mail (Docker Mailserver): SMTP + submission + IMAPS. Inbound 25
  # can be provider-blocked on some VPSes — these are open so mail works the
  # moment the provider allows it.
  ufw allow 25/tcp >/dev/null 2>&1
  ufw allow 465/tcp >/dev/null 2>&1
  ufw allow 587/tcp >/dev/null 2>&1
  ufw allow 993/tcp >/dev/null 2>&1
  # Nextcloud Talk: TURN/STUN + relay range (talk.$DOMAIN must stay DNS-only).
  ufw allow 3478/udp >/dev/null 2>&1
  ufw allow 3478/tcp >/dev/null 2>&1
  ufw allow 5349/tcp >/dev/null 2>&1
  ufw allow 49160:49200/udp >/dev/null 2>&1
  ufw allow 49160:49200/tcp >/dev/null 2>&1
  echo y | ufw enable >/dev/null 2>&1 || true

  save_state
  chmod 600 "$STATE" 2>/dev/null || true
}

# ────────────────────────────── Phase 2 (stack) ───────────────────────────

ensure_repo() {
  if [ -d "$REPO/.git" ]; then
    # Repo already present (re-run or pre-cloned): leave alone an origin that
    # already points at this repo, whatever its protocol — rewriting it to HTTPS
    # on every run clobbers an SSH origin, and `make git-push` needs the key
    # that goes with it.
    local cur
    cur="$(git -C "$REPO" remote get-url origin 2>/dev/null || true)"
    case "$cur" in
      *github.com[:/]"$GITHUB_USER/$REPO_NAME".git) ;;
      *) git -C "$REPO" remote set-url origin "https://github.com/$GITHUB_USER/$REPO_NAME.git" 2>/dev/null || true ;;
    esac
    log "repo present at $REPO"
    return
  fi
  mkdir -p /root/github
  # Public repo: clone over HTTPS — no SSH key has to be added to GitHub.
  if git clone https://github.com/$GITHUB_USER/$REPO_NAME.git "$REPO" >>"$LOG" 2>&1; then
    git -C "$REPO" remote set-url origin https://github.com/$GITHUB_USER/$REPO_NAME.git
  else
    fail clone "repo clone failed — check network/DNS, then re-run"
    exit 1
  fi
}

prep_dirs() {
  # All external (untracked) state lives under $DATA = $REPO/data, matching
  # the compose bind mounts; the repo tree itself stays clean (.gitignore has /data/).
  mkdir -p $ROOT/data/cloud/html \
               $ROOT/data/cloud/users \
               $ROOT/data/vault/data \
               $ROOT/data/kuma/data \
               $ROOT/data/mailserver/data \
               $ROOT/data/mailserver/state \
               $ROOT/data/mailserver/logs \
               $ROOT/data/mailserver/config \
               $ROOT/data/mailserver/roundcube \
               $ROOT/data/pgdata \
               $ROOT/data/talk \
               $ROOT/data/download \
               $ROOT/data/www
  # The web root is INSTANCE DATA (the repo ships no pages): seed a minimal
  # placeholder homepage ONCE so www.$DOMAIN never falls through to the bare
  # "ok" stub. Existing pages are never touched — the operator owns this dir.
  if [ ! -f "$ROOT/data/www/index.html" ]; then
    printf '<!doctype html>\n<html lang="en"><head><meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>%s</title></head><body>\n<h1>%s</h1>\n<p>This is the placeholder homepage. Drop your pages in <code>%s/www</code> — they are served at the vhost roots (<code>www.%s</code>, <code>tail.%s</code>) and are never overwritten by a render.</p>\n</body></html>\n' \
      "$DOMAIN" "$DOMAIN" "$DATA" "$DOMAIN" "$DOMAIN" > "$ROOT/data/www/index.html"
  fi
  sudo chown -R 33:33 $ROOT/data/cloud/html $ROOT/data/cloud/users
  sudo chown -R 1000:1000 $ROOT/data/vault/data
  sudo chown -R 5000:5000 $ROOT/data/mailserver/data $ROOT/data/mailserver/state $ROOT/data/mailserver/logs
  sudo chown -R 33:33 $ROOT/data/mailserver/roundcube
  # root-owned: talk configs (talk-gen), the public drop folder and the
  # instance web root (read-only from the edge container).
  # pgdata stays root-owned — the postgres entrypoint chowns it on first boot.
  sudo chown -R root:root $ROOT/data/talk \
    $ROOT/data/download \
    $ROOT/data/www
}

write_instance_conf() {
  # data/instance.conf is the ONE place this instance's values live: templates
  # are rendered from it (make render) and scripts read it (scripts/lib/instance.sh).
  # Values we do not own here (SERVER_IP, EMAIL, TIMEZONE) are PRESERVED from an
  # existing file — re-running install.sh must never wipe them.
  local f="$DATA/instance.conf" keep=""
  mkdir -p "$DATA"
  [ -f "$f" ] && keep=$(grep -E '^(SERVER_IP|EMAIL|TIMEZONE)=' "$f" || true)
  {
    echo "# data/instance.conf — the values for THIS host (untracked, mode 0600)."
    echo "# Written by scripts/install/install.sh; see config/instance.defaults for what"
    echo "# each token means. Edit by hand and run 'make render' to apply."
    printf 'DOMAIN=%s\n' "$DOMAIN"
    printf 'HOSTNAME=%s\n' "${NODE_NAME:-$(hostname -s)}"
    printf 'OPERATOR=%s\n' "root"
    # Written only when it is real: a placeholder here would render
    # {{GITHUB_USER}} into vhosts as 'exampleuser' instead of staying loud.
    [ -n "${GITHUB_USER:-}" ] && [ "$GITHUB_USER" != "exampleuser" ] \
      && printf 'GITHUB_USER=%s\n' "$GITHUB_USER"
    printf 'REPO_NAME=%s\n' "${REPO_NAME:-$(basename "$REPO")}"
    printf 'REPO_DIR=%s\n' "$REPO"
    printf 'DATA_DIR=%s\n' "$DATA"
    printf 'LOG_DIR=%s\n' "$LOG_DIR"
    printf 'STATE_DIR=%s\n' "$STATE_DIR"
    [ -n "$keep" ] && printf '%s\n' "$keep"
  } > "$f"
  chmod 600 "$f"
  log "  instance.conf written ($f) — every template renders from it"
  # compose gets the same values through the marked block in each .env
  bash "$REPO/scripts/render/render-all.sh" >>"$LOG" 2>&1 || fail render
}

seed_stack() {
  cd "$REPO" || exit 1
  # The repo already carries the canonical naming (modules/caddy,
  # container $DOMAIN, vhosts/<host>.caddy, user root) — no domain
  # renames apply. Fresh-install state: Nextcloud admin creds, stack
  # secrets, goose secret.
  # Admin creds live in the SAME file talk-gen fills with the stack secrets, so
  # this is per-key and never "write the file only if it is absent": `make
  # render` creates modules/nextcloud/.env first (instance values block), the
  # existence guard therefore never fired, compose interpolated BOTH vars as
  # empty and the image entrypoint refused to install — its fallback is
  # "Next step: Access your instance to finish the web-based installation!"
  # and `occ` then only ever answers "Set an admin Login." Nextcloud stayed
  # uninstalled and the whole occ wiring below was skipped (2026-09-25).
  local ncen=modules/nextcloud/.env
  [ -f "$ncen" ] || { umask 077; : >"$ncen"; }
  chmod 600 "$ncen"
  if ! grep -q '^NEXTCLOUD_ADMIN_PASSWORD=' "$ncen"; then
    NEXTCLOUD_ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)
    grep -q '^NEXTCLOUD_ADMIN_USER=' "$ncen" || echo 'NEXTCLOUD_ADMIN_USER=admin' >>"$ncen"
    echo "NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD" >>"$ncen"
  fi
  # Read the creds back so the summary prints the password actually in use
  # (older installs may already have them, and this run must not print a
  # freshly generated value that was never written).
  NEXTCLOUD_ADMIN_USER=$(sed -n 's/^NEXTCLOUD_ADMIN_USER=//p' "$ncen" | tail -1)
  NEXTCLOUD_ADMIN_PASSWORD=$(sed -n 's/^NEXTCLOUD_ADMIN_PASSWORD=//p' "$ncen" | tail -1)
  # Stack secrets (PostgreSQL, Redis, signaling, TURN, SMTP mailbox) +
  # Talk service configs — idempotent, appends only missing keys.
  log "  nextcloud stack secrets via talk-gen"
  make talk-gen >>"$LOG" 2>&1 || fail talk_gen
  # The goose server secret lives OUTSIDE the repo (root:root 0640) and is read by
  # the unit through EnvironmentFile= — never written into a tracked file.
  log "  goose service secret -> /etc/goose/goose.env"
  if [ ! -s /etc/goose/goose.env ]; then
    sudo install -d -m 0755 /etc/goose
    printf 'GOOSE_SERVER__SECRET_KEY=%s\n' "$(openssl rand -hex 32)" | sudo tee /etc/goose/goose.env >/dev/null
    sudo chown root:"root" /etc/goose/goose.env
    sudo chmod 0640 /etc/goose/goose.env
  fi
  # Vaultwarden SMTP sender (vaultwarden@$DOMAIN) — SMTP vars for the
  # compose interpolation; the mailbox itself is created after the
  # mailserver container is up (see vaultwarden_setup). Idempotent PER KEY —
  # never "write the file only if it is absent": `make render` already creates
  # modules/vaultwarden/.env (instance values, appended under the
  # '# >>> instance values' banner), so a file-existence guard skipped this
  # whole block, compose interpolated every SMTP_* to empty, vaultwarden
  # crash-looped on "SMTP_SECURITY is invalid" and vaultwarden_setup hit an
  # unbound $SMTP_PASSWORD (2026-09-25).
  local vwenv=modules/vaultwarden/.env
  [ -f "$vwenv" ] || { umask 077; : >"$vwenv"; }
  chmod 600 "$vwenv"
  vwset() { grep -q "^$1=" "$vwenv" || echo "$1=$2" >>"$vwenv"; }
  # starttls is the only value Vaultwarden accepts for this variable besides
  # force_tls/off — it must never be left empty.
  vwset SMTP_HOST "mail.$DOMAIN"
  vwset SMTP_PORT 587
  vwset SMTP_SECURITY starttls
  vwset SMTP_USERNAME "vaultwarden@$DOMAIN"
  vwset SMTP_PASSWORD "$(openssl rand -hex 16)"
  vwset SMTP_FROM "vaultwarden@$DOMAIN"
  vwset SMTP_FROM_NAME Vaultwarden
  vwset SMTP_AUTH_MECHANISM Login
}

docker_net() {
  docker network create net --subnet=172.22.0.0/16 >>"$LOG" 2>&1 || true
}

caddy_data() {
  # The compose env_file path is $(REPO)/caddy_data (sibling of repo/), not inside the clone.
  sudo mkdir -p $ROOT/data/caddy_data
  printf 'CF_API_TOKEN=%s\n' "$CF_API_TOKEN" | sudo tee $ROOT/data/caddy_data/CF_API_TOKEN >/dev/null
  sudo chown -R 201:201 $ROOT/data/caddy_data
  # 0711, never the root umask's 0700: `docker compose` runs as root and
  # reads env_file host-side, so it needs +x on the dir or it dies with
  # "open .../CF_API_TOKEN: permission denied" and Caddy never starts.
  sudo chmod 0711 $ROOT/data/caddy_data
  sudo chown root:root $ROOT/data/caddy_data/CF_API_TOKEN
  sudo chmod 0644 $ROOT/data/caddy_data/CF_API_TOKEN
}

host_services() {
  [ -n "${TS_IP:-}" ] || fail ts_ip
  # The tracked 10-tailnet.conf keeps a PLACEHOLDER address — install-config
  # renders the live Tailscale IP in at deploy time, so the repo file is never
  # mutated and no instance-specific address is ever committed.
  make install-config >>"$LOG" 2>&1 || fail install_config
  # fail2ban: on trixie the default file backend finds no /var/log/auth.log and
  # the unit exits 255. Our jail.d/sshd.conf ships backend=systemd; restart and
  # verify so a silently-dead jail can never pass as hardened.
  systemctl restart fail2ban >>"$LOG" 2>&1 || true
  # `systemctl restart` returns while the unit is still activating, and
  # install-config restarts fail2ban again seconds later — so poll for the
  # server + the sshd jail instead of judging the unit on the first look
  # (2026-09-25: the tag fired ~0.3 s before the jail came up and then sat in
  # the summary as a phantom "not running" error on an active fail2ban).
  local i=0
  while [ $i -lt 30 ]; do
    systemctl is-active --quiet fail2ban && fail2ban-client status sshd >/dev/null 2>&1 && break
    sleep 1; i=$((i+1))
  done
  systemctl is-active --quiet fail2ban || fail fail2ban
  fail2ban-client status sshd >/dev/null 2>&1 || fail fail2ban
}

containers_up() {
  log "  building Caddy image (caddy:local) — ~3 min on a cold cache"
  # The dok-recreate recipe already falls back to docker build + compose up
  # when compose's buildx is too old (Debian trixie), so no manual fallback
  # is needed here.
  make dok-recreate-caddy >>"$LOG" 2>&1 || fail caddy
  # PostgreSQL first — the nextcloud entrypoint's fresh install needs the DB
  # reachable (POSTGRES_HOST from .env, set by talk-gen above). Caddy's
  # DNS-01 issuance runs at startup, so the mail/turn certs the talk stack
  # and mailserver need are on disk by the time they start. Modules respect
  # the install-time choice (default: everything ON).
  if [ "${MOD_CLOUD:-true}" = "true" ]; then
    make dok-recreate-nextcloud-db >>"$LOG" 2>&1 || fail nextcloud_db
    make dok-recreate-nextcloud   >>"$LOG" 2>&1 || fail nextcloud
  fi
  [ "${MOD_VAULT:-true}"   = "true" ] && { make dok-recreate-vaultwarden >>"$LOG" 2>&1 || fail vaultwarden; }
  [ "${MOD_MONITOR:-true}" = "true" ] && { make dok-recreate-uptimekuma  >>"$LOG" 2>&1 || fail kuma; }
  [ "${MOD_MAIL:-true}"    = "true" ] && { make dok-recreate-mailserver  >>"$LOG" 2>&1 || fail mailserver; }
}

kuma_seed() {
  # Wait for the SCHEMA, not for the file. Kuma 2.5+ serves its "Setup
  # Database" wizard (port open, healthcheck green, kuma.db still 0 bytes) when
  # it can neither read db-config.json nor find a kuma.db — the compose file
  # now sets UPTIME_KUMA_DB_TYPE=sqlite so the main server starts and creates
  # the tables. Polling `test -f` was a trap: the poll timed out, sqlite3 then
  # CREATED an empty kuma.db and every seed statement failed with "no such
  # table" (2026-09-25).
  local i=0 ready=""
  while [ $i -lt 150 ]; do
    if docker exec uptimekuma sqlite3 /app/data/kuma.db \
         "SELECT 1 FROM sqlite_master WHERE type='table' AND name='user';" 2>/dev/null | grep -q 1; then
      ready=1; break
    fi
    sleep 2; i=$((i+2))
  done
  if [ -z "$ready" ]; then
    fail kuma_seed "kuma.db has no schema after 5 min (Kuma still in Setup Database)"
    return
  fi
  KUMA_PASS=$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)
  local n
  n=$(docker exec uptimekuma sqlite3 /app/data/kuma.db "SELECT COUNT(*) FROM user WHERE username='admin';" 2>/dev/null | tr -d '\n')
  if [ "$n" = "0" ]; then
    local HASH
    HASH=$(htpasswd -bnBC 10 "" "$KUMA_PASS" 2>/dev/null | tr -d ':\n')
    if [ -n "$HASH" ]; then
      docker exec uptimekuma sqlite3 /app/data/kuma.db \
        "INSERT OR IGNORE INTO user (username,password,active,timezone) VALUES ('admin','$HASH',1,'UTC');" \
        >>"$LOG" 2>&1 || fail kuma_admin
    fi
  fi
  docker exec -i uptimekuma sqlite3 /app/data/kuma.db < modules/uptimekuma/seed-monitors.sql \
    >>"$LOG" 2>&1 || fail kuma_seed
}

# Idempotently create one mailserver mailbox, retrying until it takes.
# Password comes on stdin twice (value + confirmation), as `setup email add`
# expects. Two traps made the old one-shot call fail: docker-mailserver exits
# ~2 min after start when no account exists yet ("You need at least one mail
# account to start Dovecot (120s left...)") and compose restarts it, so the
# command can land in a dead/restarting window; and a single attempt gives no
# second chance once the installer has moved on (2026-09-25: both mailboxes
# uncreated, leaving the whole mail stack with no account).
# Returns non-zero only after a 5-minute retry window.
mailbox_add() {
  local addr="$1" pass="${2:-}" i=0
  while [ $i -lt 60 ]; do
    if docker exec mailserver setup email list 2>/dev/null \
         | grep -qiE "^[* ] *${addr//./\\.}( |\$|\[)"; then
      return 0
    fi
    if printf '%s\n%s\n' "$pass" "$pass" \
         | docker exec -i mailserver setup email add "$addr" >/dev/null 2>&1; then
      log "  mailbox created: $addr"
      return 0
    fi
    sleep 5; i=$((i+5))
  done
  return 1
}

# Post-boot Nextcloud occ wiring: Talk signaling + TURN registration, NC
# outbound SMTP (nextcloud@$DOMAIN sender mailbox), background cron. All
# steps are idempotent (safe to re-run; never clobbers operator settings).
# Requires the nextcloud + mailserver containers (called after containers_up).
nextcloud_setup() {
  cd "$REPO" || exit 1
  . modules/nextcloud/.env
  # The image entrypoint only installs Nextcloud while /var/www/html has no
  # version.php. A first attempt that fails (empty NEXTCLOUD_ADMIN_* from a
  # skipped seed, DB not yet up, …) still leaves version.php behind, and every
  # later start reads that as "already at the image version" and silently
  # skips BOTH install and upgrade: the container reports healthy, occ reports
  # "installed: false", and no occ step below ever runs (2026-09-25). So do
  # the install here when occ says it is missing — same options the entrypoint
  # would use, taken from the same .env.
  if ! docker exec -u www-data nextcloud php occ status 2>/dev/null | grep -q "installed: true"; then
    log "  nextcloud reports not-installed — running occ maintenance:install"
    if docker exec -u www-data nextcloud php occ maintenance:install -n \
         --admin-user "${NEXTCLOUD_ADMIN_USER:-admin}" \
         --admin-pass "${NEXTCLOUD_ADMIN_PASSWORD:-}" \
         --data-dir /data \
         --database pgsql --database-name "$POSTGRES_DB" \
         --database-user "$POSTGRES_USER" --database-pass "$POSTGRES_PASSWORD" \
         --database-host "$POSTGRES_HOST" >>"$LOG" 2>&1; then
      log "  nextcloud installed"
      # occ does not apply NEXTCLOUD_TRUSTED_DOMAINS (the entrypoint does) —
      # without this entry https://cloud.$DOMAIN answers 400 untrusted domain.
      docker exec -u www-data nextcloud php occ config:system:set trusted_domains 1 \
        --value "cloud.$DOMAIN" >/dev/null 2>&1 || true
    else
      fail nextcloud_setup "occ maintenance:install failed — see $LOG"
    fi
  fi
  # Then wait for a usable instance: a cold cache (fresh image pull + the
  # ~3 min Caddy build hogging the box) blew the old 3-minute budget, so every
  # occ step below — Talk signaling/TURN, SMTP, cron — silently never ran
  # (2026-09-25). 8 minutes, and say so in the log while waiting.
  local i=0
  while [ $i -lt 240 ]; do
    docker exec -u www-data nextcloud php occ status 2>/dev/null | grep -q "installed: true" && break
    [ $((i % 30)) -eq 0 ] && log "  waiting for nextcloud to finish installing (${i}s)"
    sleep 2; i=$((i+2))
  done
  if ! docker exec -u www-data nextcloud php occ status 2>/dev/null | grep -q "installed: true"; then
    fail nextcloud_setup "nextcloud not installed/ready after 8 min"
    return
  fi

  # Talk app (spreed) — bundled in the image; enable if disabled.
  docker exec -u www-data nextcloud php occ app:enable spreed >/dev/null 2>&1 || true

  # NC outbound SMTP sender mailbox — create if missing (secrets from .env).
  . modules/nextcloud/.env
  mailbox_add "nextcloud@$DOMAIN" "${SMTP_PASSWORD:-}" \
    || fail nextcloud_setup "mailbox nextcloud@$DOMAIN not created"

  # trusted_proxies must be a real ARRAY (NC 34 setup check) — the image
  # env TRUSTED_PROXIES writes a comma-joined string into index 0, which
  # breaks the brute-force throttle. The compose no longer carries it; set
  # it here as indexed entries (Caddy's net subnet + Cloudflare edge ranges).
  docker exec -u www-data nextcloud php occ config:system:delete trusted_proxies >/dev/null 2>&1 || true
  local p i=0
  for p in 172.22.0.0/16 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32; do
    docker exec -u www-data nextcloud php occ config:system:set trusted_proxies "$i" --value "$p" >/dev/null 2>&1
    i=$((i+1))
  done

  # NC SMTP settings — host/port/name/from/domain only when unset (never
  # clobber operator config); secure + authtype fixed unconditionally (the
  # 2026-08-31 "Email could not be sent" cause was secure=ssl on port 587).
  # Output redirected: occ config:system:set echoes secret values to stdout.
  if [ -z "$(docker exec -u www-data nextcloud php occ config:system:get mail_smtphost 2>/dev/null | tr -d '\n')" ]; then
    docker exec -u www-data nextcloud php occ config:system:set mail_smtphost --value "mail.$DOMAIN" >/dev/null 2>&1
    docker exec -u www-data nextcloud php occ config:system:set mail_smtpport --value 587 >/dev/null 2>&1
    docker exec -u www-data nextcloud php occ config:system:set mail_smtpname --value "nextcloud@$DOMAIN" >/dev/null 2>&1
    docker exec -u www-data nextcloud php occ config:system:set mail_smtppassword --value "$SMTP_PASSWORD" >/dev/null 2>&1
    docker exec -u www-data nextcloud php occ config:system:set mail_from_address --value nextcloud >/dev/null 2>&1
    docker exec -u www-data nextcloud php occ config:system:set mail_domain --value "$DOMAIN" >/dev/null 2>&1
  fi
  docker exec -u www-data nextcloud php occ config:system:set mail_smtpsecure --value tls >/dev/null 2>&1
  docker exec -u www-data nextcloud php occ config:system:set mail_smtpauthtype --value LOGIN >/dev/null 2>&1
  # Without mail_smtpauth=true NC connects anonymously and the submission
  # server rejects every send ("Client host rejected: Access denied") — the
  # UI test email fails even though the credentials are valid.
  docker exec -u www-data nextcloud php occ config:system:set mail_smtpauth --value true >/dev/null 2>&1

  # Single-PHP instance: serverid (int 0-511) silences the "Configuration
  # server ID" setup check; AppAPI is disabled — no external apps are used
  # (the "AppAPI default deploy daemon" check only fires while it's enabled).
  if [ -z "$(docker exec -u www-data nextcloud php occ config:system:get serverid 2>/dev/null | tr -d '\n')" ]; then
    docker exec -u www-data nextcloud php occ config:system:set serverid --value 1 --type integer >/dev/null 2>&1 || true
  fi
  docker exec -u www-data nextcloud php occ app:disable app_api >/dev/null 2>&1 || true

  # Talk signaling — ONE entry (the public URL): NC 34 deprecates multiple
  # high-performance backends. Clients get wss://talk.$DOMAIN/signaling; the
  # signaling server reaches NC back via its own [backend1] urls (extra_hosts),
  # so no internal URL registration is needed.
  local sig
  sig=$(docker exec -u www-data nextcloud php occ talk:signaling:list 2>/dev/null)
  if ! echo "$sig" | grep -q "https://talk.$DOMAIN/signaling"; then
    docker exec -u www-data nextcloud php occ talk:signaling:add "https://talk.$DOMAIN/signaling" "$SIGNALING_SECRET" >/dev/null 2>&1 || true
  fi
  docker exec -u www-data nextcloud php occ talk:signaling:remove "http://172.22.0.12:8080" >/dev/null 2>&1 || true

  # Talk TURN/STUN — udp+tcp on 3478, tls on 5349 (secret matches turnserver.conf).
  local trn
  trn=$(docker exec -u www-data nextcloud php occ talk:turn:list 2>/dev/null)
  # talk:turn:add <schemes> <server> <protocols> — protocols are POSITIONAL;
  # the old --udp/--tcp flags don't exist, so the call always failed and TURN
  # was never registered.
  if ! echo "$trn" | grep -q "talk.$DOMAIN:3478"; then
    docker exec -u www-data nextcloud php occ talk:turn:add turn "talk.$DOMAIN:3478" "udp,tcp" --secret "$TURN_SECRET" >/dev/null 2>&1 || true
  fi
  if ! echo "$trn" | grep -q "talk.$DOMAIN:5349"; then
    docker exec -u www-data nextcloud php occ talk:turn:add turns "talk.$DOMAIN:5349" "tcp" --secret "$TURN_SECRET" >/dev/null 2>&1 || true
  fi

  # Background jobs via the host cron (config/cron/nextcloud, installed by install-config).
  docker exec -u www-data nextcloud php occ background:cron >/dev/null 2>&1 || true

  # Silence the recurring "Skipping updater backup clean-up" warning: the
  # cleanup job expects /data/updater-<instanceid>/backups to exist.
  IID=$(docker exec -u www-data nextcloud php occ config:system:get instanceid 2>/dev/null | tr -d '\n')
  [ -n "$IID" ] && docker exec -u www-data nextcloud sh -c "mkdir -p /data/updater-$IID/backups" >/dev/null 2>&1 || true

  # Recovery manifest: users + quotas ($DATA/cloud/recovery/users.txt, kept
  # OUTSIDE the repo — instance state, generated by `make nc-capture`). Missing
  # users are created with a generated password printed ONCE at the end (the
  # pre-wipe passwords lived in the wiped DB — hand the new ones to the users).
  if [ -f "$MANIFEST_DIR/users.txt" ]; then
    while IFS='|' read -r uid quota email disp _; do
      [ -n "$uid" ] || continue
      case "$uid" in \#*) continue ;; esac
      if ! docker exec -u www-data nextcloud php occ user:list 2>/dev/null | grep -q "^  - $uid:"; then
        NP=$(openssl rand -base64 12 | tr -d '/+=' | head -c 12)
        docker exec -e OC_PASS="$NP" -u www-data nextcloud php occ user:add --password-from-env "$uid" >/dev/null 2>&1 \
          && echo "[install] new user $uid — password: $NP (share with them)"
      fi
      [ -n "$quota" ] && docker exec -u www-data nextcloud php occ user:setting "$uid" files quota "$quota" >/dev/null 2>&1
      [ -n "$email" ] && docker exec -u www-data nextcloud php occ user:setting "$uid" settings email "$email" >/dev/null 2>&1
      [ -n "$disp" ] && docker exec -u www-data nextcloud php occ user:setting "$uid" settings displayname "$disp" >/dev/null 2>&1
    done < "$MANIFEST_DIR/users.txt"
  fi

  # The vhost Host must be trusted or NC 400s every request on it. The compose
  # env NEXTCLOUD_TRUSTED_DOMAINS seeds cloud.$DOMAIN on a fresh DB — writing
  # the bare $DOMAIN into index 1 clobbers it.
  if ! docker exec -u www-data nextcloud php occ config:system:get trusted_domains 2>/dev/null | grep -qx "cloud.$DOMAIN"; then
    docker exec -u www-data nextcloud php occ config:system:set trusted_domains 1 --value "cloud.$DOMAIN" >/dev/null 2>&1 || true
  fi

  # Recovery manifest: apps enabled beyond the image defaults
  # ($DATA/cloud/recovery/apps.txt).
  if [ -f "$MANIFEST_DIR/apps.txt" ]; then
    while read -r app; do
      [ -n "$app" ] || continue
      case "$app" in \#*) continue ;; esac
      docker exec -u www-data nextcloud php occ app:enable "$app" >/dev/null 2>&1 || true
    done < "$MANIFEST_DIR/apps.txt"
  fi

  # Fresh installs ship with pending maintenance work that the setup check
  # surfaces as warnings — run it all up front so a fresh install is clean:
  #   - mimetype migrations (occ maintenance:repair --include-expensive)
  #   - missing DB indices/columns/primary keys (the mail app adds several)
  docker exec -u www-data nextcloud php occ maintenance:repair --include-expensive >/dev/null 2>&1 || true
  docker exec -u www-data nextcloud php occ db:add-missing-indices >/dev/null 2>&1 || true
  docker exec -u www-data nextcloud php occ db:add-missing-columns >/dev/null 2>&1 || true
  docker exec -u www-data nextcloud php occ db:add-missing-primary-keys >/dev/null 2>&1 || true

  # Recovery manifest: default quota for new users (cloud/recovery/default-quota)
  if [ -f "$MANIFEST_DIR/default-quota" ]; then
    DQ=$(grep -v '^#' "$MANIFEST_DIR/default-quota" | head -1)
    [ -n "$DQ" ] && docker exec -u www-data nextcloud php occ config:app:set files default_quota --value "$DQ" >/dev/null 2>&1 || true
  fi

  # Recovery manifest: groups (cloud/recovery/groups.txt)
  if [ -f "$MANIFEST_DIR/groups.txt" ]; then
    while IFS='|' read -r grp members _; do
      [ -n "$grp" ] || continue
      case "$grp" in \#*) continue ;; esac
      docker exec -u www-data nextcloud php occ group:addgroup "$grp" >/dev/null 2>&1 || true
      for m in ${members//,/ }; do
        [ -n "$m" ] && docker exec -u www-data nextcloud php occ group:adduser "$grp" "$m" >/dev/null 2>&1 || true
      done
    done < "$MANIFEST_DIR/groups.txt"
  fi

  # Verify what the smoke/operational docs assert.
  docker exec -u www-data nextcloud php occ config:system:get mail_smtphost 2>/dev/null | grep -q "mail.$DOMAIN" \
    || fail nextcloud_setup "mail_smtphost not set"
  docker exec -u www-data nextcloud php occ talk:signaling:list 2>/dev/null | grep -q "https://talk.$DOMAIN/signaling" \
    || fail nextcloud_setup "talk signaling not registered"
  docker exec -u www-data nextcloud php occ talk:turn:list 2>/dev/null | grep -q "talk.$DOMAIN:3478" \
    || fail nextcloud_setup "talk turn not registered"
}

# Vaultwarden SMTP sender mailbox (vaultwarden@$DOMAIN) — created after the
# mailserver container is up (called after containers_up). The SMTP vars the
# vaultwarden container uses come from modules/vaultwarden/.env (written by
# seed_stack); this step only makes the mailbox exist so auth succeeds.
vaultwarden_setup() {
  cd "$REPO" || exit 1
  . modules/vaultwarden/.env
  # ${SMTP_PASSWORD:-}: an unbound expansion here used to kill this function's
  # pipeline subshell, so the only visible symptom was "mailbox not created"
  # instead of the real fault (seed_stack had skipped writing the key). Name
  # it explicitly now (2026-09-25).
  if [ -z "${SMTP_PASSWORD:-}" ]; then
    fail vaultwarden_setup "SMTP_PASSWORD missing from modules/vaultwarden/.env"
    return
  fi
  mailbox_add "vaultwarden@$DOMAIN" "$SMTP_PASSWORD" \
    || fail vaultwarden_setup "mailbox vaultwarden@$DOMAIN not created"
}

# Publish the mailserver's DKIM key as a TXT record via the Cloudflare API —
# the whole mail-authentication stack (SPF/DKIM/DMARC + PTR) then only needs
# the operator's provider-side PTR. Runs after the mailserver is up
# (containers_up); requires ENABLE_OPENDKIM=0 in the mailserver compose
# (Rspamd signs — otherwise `setup config dkim` aborts on the conflict).
dkim_setup() {
  cd "$REPO" || exit 1
  local rec value zone id i=0
  # The mailserver restart-loops until Caddy has written its mail.$DOMAIN cert
  # (SSL_TYPE=manual) — wait for a live container, or `setup config dkim`
  # aborts and the error surfaces as a bare "keygen".
  while [ $i -lt 90 ]; do
    docker exec mailserver true >/dev/null 2>&1 && break
    sleep 2; i=$((i+2))
  done
  # rc=1 when the key already exists ("Not overwriting existing files") — the
  # idempotent case, so judge by the public key, not the exit code.
  docker exec mailserver setup config dkim domain "$DOMAIN" >/dev/null 2>&1 || true
  # *.public.txt is the BIND zone-file form and splits the key across quoted
  # lines (grepping it published a truncated key); *.public.dns.txt is the
  # single-line record, ready to publish.
  rec=$(docker exec mailserver sh -c 'cat /tmp/docker-mailserver/rspamd/dkim/*.public.dns.txt' 2>/dev/null \
    | grep -oE 'p=[A-Za-z0-9+/=]+' | sed 's/p=//' | tr -d '\n')
  [ -n "$rec" ] || fail dkim_setup "no public key"
  value="v=DKIM1; k=rsa; p=$rec"
  zone=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['result'][0]['id'] if d.get('result') else '')" 2>/dev/null)
  [ -n "$zone" ] || fail dkim_setup "zone lookup"
  # drop any stale mail._domainkey TXT records, then publish ours
  for id in $(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
      "https://api.cloudflare.com/client/v4/zones/$zone/dns_records?type=TXT&name=mail._domainkey.$DOMAIN" \
      | python3 -c "import sys,json; [print(r['id']) for r in (json.load(sys.stdin).get('result') or [])]" 2>/dev/null); do
    curl -s -X DELETE -H "Authorization: Bearer $CF_API_TOKEN" \
      "https://api.cloudflare.com/client/v4/zones/$zone/dns_records/$id" >/dev/null
  done
  python3 - "$CF_API_TOKEN" "$zone" "$value" <<'EOF' || fail dkim_setup "record publish"
import sys, json, urllib.request
tok, zone, val = sys.argv[1], sys.argv[2], sys.argv[3]
req = urllib.request.Request(f"https://api.cloudflare.com/client/v4/zones/{zone}/dns_records",
  data=json.dumps({"type": "TXT", "name": "mail._domainkey", "content": val, "ttl": 1, "proxied": False}).encode(),
  headers={"Authorization": "Bearer " + tok, "Content-Type": "application/json"}, method="POST")
sys.exit(0 if json.loads(urllib.request.urlopen(req).read().decode()).get("success") else 1)
EOF
  log "DKIM published: mail._domainkey TXT for $DOMAIN (PTR remains provider-side)"
}

ssl_mode_full() {
  # API first (needs Zone Settings read on the token); fall back to a
  # behavior probe — Flexible/Off makes CF reach the origin over HTTP and
  # Caddy answers a 308 back to the same https URL (redirect loop).
  local mode hdrs code loc
  mode=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/settings/ssl" 2>/dev/null \
    | jq -r '.result.value // empty' 2>/dev/null)
  case "$mode" in full|strict) return 0 ;; esac
  [ -n "$mode" ] && return 1
  hdrs=$(curl -sI --max-time 15 "https://cloud.$DOMAIN" 2>/dev/null | tr -d '\r')
  code=$(echo "$hdrs" | awk 'NR==1{print $2}')
  loc=$(echo "$hdrs" | awk 'tolower($1)=="location:"{print $2; exit}')
  [ "$code" = "308" ] && [[ "$loc" == *"cloud.$DOMAIN"* ]] && return 1
  return 0
}

  cf_dns() {
  VPS_IP=$(curl -s4 ifconfig.me)
  ZONE_ID=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" | jq -r '.result[0].id // empty')
  if [ -z "$ZONE_ID" ]; then
    fail zone
    return
  fi
  cf_record() { # $1=host $2=proxied(true/false)
    local rid
    rid=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
      "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=A&name=$1.$DOMAIN" | jq -r '.result[0].id // empty')
    if [ -z "$rid" ]; then
      curl -s -X POST -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
        "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
        -d "{\"type\":\"A\",\"name\":\"$1.$DOMAIN\",\"content\":\"$VPS_IP\",\"ttl\":1,\"proxied\":$2}" \
        >>"$LOG" 2>&1 || fail "dns_$1"
    fi
  }
  # proxied (orange cloud): cloud/vault/kuma/www. talk rides on the cloud door.
  for h in cloud vault kuma www; do
    case "$h" in
      cloud) [ "${MOD_CLOUD:-true}" = "true" ] && cf_record "$h" true;;
      vault) [ "${MOD_VAULT:-true}" = "true" ] && cf_record "$h" true;;
      kuma)  [ "${MOD_MONITOR:-true}" = "true" ] && cf_record "$h" true;;
      www)   cf_record "$h" true;;
    esac
  done
  # talk/mail MUST be DNS-only (grey cloud): TURN relays media over
  # UDP/TCP 3478/5349 + 49160-49200 and SMTP/IMAP also bypass the CF proxy
  # (HTTP(S) only). Caddy still gets their LE certs via DNS-01.
  [ "${MOD_CLOUD:-true}" = "true" ] && cf_record talk false
  [ "${MOD_MAIL:-true}"  = "true" ] && cf_record mail false
  curl -s -X PATCH -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
    "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/settings/ssl" -d '{"value":"full"}' >>"$LOG" 2>&1 || true
  # DNS-only tokens can't set SSL mode; surface it as an expected manual step.
  if ! ssl_mode_full; then
    fail sslmode
  fi
}

# Issuer of the cert Caddy presents for one vhost, polled while ACME finishes.
cert_issuer() {
  local h="$1" i=0 iss=""
  while [ $i -lt 45 ]; do
    iss=$(echo | timeout 10 openssl s_client -connect 127.0.0.1:443 -servername "$h.$DOMAIN" 2>/dev/null \
      | openssl x509 -noout -issuer 2>/dev/null | cut -d'=' -f2-)
    case "$iss" in *"Let's Encrypt"*) break;; esac
    i=$((i+2)); sleep 2
  done
  echo "$iss"
}

issue_certs() {
  local hosts="" h iss pending=()
  hosts="www"
  [ "${MOD_CLOUD:-true}" = "true" ]   && hosts="$hosts cloud talk"
  [ "${MOD_VAULT:-true}" = "true" ]   && hosts="$hosts vault"
  [ "${MOD_MONITOR:-true}" = "true" ] && hosts="$hosts kuma"
  [ "${MOD_MAIL:-true}" = "true" ]    && hosts="$hosts mail"
  for h in $hosts; do
    curl -sk --resolve "$h.$DOMAIN:443:127.0.0.1" -o /dev/null "https://$h.$DOMAIN/" >>"$LOG" 2>&1 || true
    sleep 3
  done
  # The trigger requests above only wake Caddy up — the first DNS-01 issuance
  # is not instant, so cert_issuer polls before declaring failure.
  for h in $hosts; do
    case "$(cert_issuer "$h")" in *"Let's Encrypt"*) ;; *) pending+=("$h");; esac
  done
  # Caddy's ACME retry backoff can leave a single order stuck (observed on
  # kuma.$DOMAIN: every other vhost issued, kuma's lock kept retrying) — one
  # restart re-attempts the pending identifiers.
  if [ ${#pending[@]} -gt 0 ]; then
    log "  ${#pending[@]} cert(s) pending (${pending[*]}) — restarting Caddy to re-attempt"
    # The container is named `caddy` (compose container_name), not $DOMAIN —
    # restarting "$DOMAIN" always failed with "No such container" and the
    # re-attempt never happened (2026-09-25).
    docker restart caddy >>"$LOG" 2>&1 || true
    sleep 5
  fi
  for h in $hosts; do
    iss=$(cert_issuer "$h")
    case "$iss" in
      *"Let's Encrypt"*) ;;
      *) fail "cert_$h" "issuer was: $iss";;
    esac
  done
}

# Old-project references must not survive in anything the installer deploys
# (compose files, host config, Makefile, recipes). docs/ and scripts/ are out
# of scope by design: docs record the rename as history, and the scripts
# (this installer, the rewrite/import tooling) name the old project by nature
# — counting them made the check unsatisfiable on the repo's own tree.
sweep_hits() {
  grep -rlI '$GITHUB_USER' "$REPO" \
    --exclude-dir=.git --exclude-dir=docs --exclude-dir=archives --exclude-dir=scripts 2>/dev/null || true
}

sweep() {
  [ -z "$(sweep_hits)" ] || fail sweep
}

phase_stack() {
  log "Phase 2 (stack): repo, host config, containers, DNS, certs"
  # Fail fast: the Cloudflare zone must already exist (the script cannot
  # create one — that needs nameservers pointing at Cloudflare).
  if [ -z "$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
        "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" | jq -r '.result[0].id // empty')" ]; then
    fail zone "create the zone in the CF dashboard (point your nameservers there), then re-run"
    exit 1
  fi
  ensure_repo
  prep_dirs
  seed_stack
  docker_net
  caddy_data
  cf_dns
  host_services
  containers_up
  # per-module setup, in dependency order (default: everything ON)
  if [ "${MOD_CLOUD:-true}" = "true" ]; then
    nextcloud_setup
  fi
  [ "${MOD_VAULT:-true}" = "true" ] && vaultwarden_setup
  [ "${MOD_MAIL:-true}" = "true" ] && dkim_setup
  issue_certs
  [ "${MOD_MONITOR:-true}" = "true" ] && kuma_seed
  sweep
}

# ──────────────────────── error problems + hints ──────────────────────────

problem() {
  case "$1" in
    apt)            echo "apt packages not installed" ;;
    goose)          echo "goose binary not installed" ;;
    user)           echo "user 'root' not created" ;;
    ssh_keys)       echo "no SSH key on the box although the installer asks for one up front" ;;
    render)         echo "template rendering failed (see make render)" ;;
    tailscale)      echo "tailscale binary not installed" ;;
    tailscale_up)   echo "tailscale did not connect" ;;
    ts_ip)          echo "no tailscale IP assigned" ;;
    install_config) echo "host services are not up (make install-config failed)" ;;
    fail2ban)       echo "fail2ban is not running (sshd jail dead)" ;;
    caddy)          echo "caddy container is not running" ;;
    nextcloud)      echo "nextcloud container is not running (or talk-hpb/talk-relay are down)" ;;
    nextcloud_db)   echo "postgresql container is not running (docker-compose.db.yml)" ;;
    vaultwarden)    echo "vaultwarden container is not running" ;;
    kuma)           echo "uptimekuma container is not running" ;;
    mailserver)     echo "mailserver container is not running (mail platform)" ;;
    datadirectory)  echo "nextcloud datadirectory is not /data" ;;
    talk_gen)       echo "nextcloud stack secrets not generated (make talk-gen failed)" ;;
    kuma_admin)     echo "uptime kuma admin user is missing" ;;
    kuma_seed)      echo "uptime kuma monitors are not seeded" ;;
    zone)           echo "Cloudflare zone '$DOMAIN' not found" ;;
    dns_*)          echo "DNS record for ${1#dns_}.$DOMAIN is missing" ;;
    cert_*)         echo "cert for ${1#cert_}.$DOMAIN is not issued by Let's Encrypt" ;;
    sweep)          echo "old project name is still referenced in the repo tree" ;;
    sslmode)        echo "Cloudflare SSL/TLS mode is not Full (or strict)" ;;
    nextcloud_setup) echo "Nextcloud occ wiring incomplete (Talk signaling/TURN, SMTP, background cron)" ;;
    dkim_setup)      echo "DKIM key / mail._domainkey TXT record not published" ;;
    vaultwarden_setup) echo "Vaultwarden SMTP sender mailbox missing (vaultwarden@$DOMAIN)" ;;
    clone)          echo "repo clone failed" ;;
    github_key)     echo "the GitHub key could not be created" ;;
    github_auth)    echo "GitHub remote access was requested but the key is not authorized / nothing was pushed" ;;
    *)              echo "$1" ;;
  esac
}

hint() {
  case "$1" in
    apt)            echo "install git curl make sudo dnsmasq ufw jq apache2-utils sqlite3 python3-yaml, plus docker with the compose plugin (docker-ce from download.docker.com on trixie), then re-check" ;;
    goose)          echo "install bzip2 first (the release is a .tar.bz2: apt-get install -y bzip2), then: curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | CONFIGURE=false GOOSE_BIN_DIR=/usr/local/bin bash, then re-check" ;;
    user)           echo "run: adduser --disabled-password --gecos '' root && usermod -aG sudo,docker root, then re-check" ;;
    ssh_keys)       echo "paste your device's public key into /root/.ssh/authorized_keys (or re-run the installer), then re-check" ;;
    tailscale)      echo "run: curl -fsSL https://tailscale.com/install.sh | sh, then re-check" ;;
    tailscale_up)   echo "check the auth key (admin console -> Settings -> Keys) and run: tailscale up --authkey=<key>, then re-check" ;;
    ts_ip)          echo "wait a few seconds, then run: tailscale ip -4, then re-check" ;;
    install_config) echo "run: make install-config in $REPO, then re-check" ;;
    fail2ban)       echo "ensure /etc/fail2ban/jail.d/sshd.conf has backend = systemd, then: systemctl restart fail2ban; fail2ban-client status sshd" ;;
    caddy)          echo "run: make dok-recreate-caddy, then re-check" ;;
    nextcloud)      echo "run: make dok-recreate-nextcloud, then re-check" ;;
    nextcloud_db)   echo "run: make dok-recreate-nextcloud-db, then re-check" ;;
    talk_gen)       echo "run: make talk-gen in $REPO, then re-check" ;;
    vaultwarden)    echo "run: make dok-recreate-vaultwarden, then re-check" ;;
    kuma)           echo "run: make dok-recreate-uptimekuma, then re-check" ;;
    mailserver)     echo "run: make dok-recreate-mailserver, then re-check" ;;
    datadirectory)  echo "run: docker exec -w /var/www/html nextcloud php occ config:system:set datadirectory --value /data, then re-check" ;;
    kuma_admin)     echo "create the admin account at https://kuma.$DOMAIN in the UI, then re-check" ;;
    kuma_seed)      echo "run: make dok-recreate-uptimekuma (UPTIME_KUMA_DB_TYPE=sqlite makes Kuma create its schema), wait for /app/data/kuma.db to have tables, then: docker exec -i uptimekuma sqlite3 /app/data/kuma.db < modules/uptimekuma/seed-monitors.sql" ;;
    zone)           echo "add $DOMAIN as a zone in the Cloudflare dashboard, then re-check" ;;
    dns_*)          echo "create an A record ${1#dns_}.$DOMAIN -> ${VPS_IP:-<VPS IP>} in Cloudflare (turn must be DNS-only/grey-cloud — TURN bypasses the proxy; the rest proxied), then re-check" ;;
    cert_*)         echo "hit https://${1#cert_}.$DOMAIN once to trigger ACME, wait a few seconds, then re-check" ;;
    sweep)          echo "rename or remove the files listed by: grep -rlI $GITHUB_USER $REPO --exclude-dir=.git --exclude-dir=docs --exclude-dir=archives --exclude-dir=scripts, then re-check" ;;
    sslmode)        echo "Cloudflare dashboard -> SSL/TLS -> Overview -> set mode to Full (or Full strict), then re-check" ;;
    nextcloud_setup) echo "run the occ steps from docs/GUIDE.md 'Ordering after a fresh deploy' (talk:signaling:add x2, talk:turn:add x2, config:system:set mail_*, background:cron) — see the nextcloud_setup function in this script, then re-check" ;;
    dkim_setup)      echo "run: docker exec mailserver setup config dkim domain $DOMAIN; ensure ENABLE_OPENDKIM=0 in the mailserver compose (Rspamd signs); verify the CF token has Zone > DNS > Edit; then dig @<zone NS> TXT mail._domainkey.$DOMAIN" ;;
    vaultwarden_setup) echo "ensure SMTP_PASSWORD (and the other SMTP_* keys) exist in modules/vaultwarden/.env — make render writes the file but not those keys — then: printf '%s\\n%s\\n' <pass> <pass> | docker exec -i mailserver setup email add vaultwarden@$DOMAIN; re-check" ;;
    clone)          echo "the clone is HTTPS (the repo is public) — check network/DNS, then re-check" ;;
    github_key)     echo "check /root/.ssh is writable (mkdir -p /root/.ssh && chmod 700 /root/.ssh), then re-check" ;;
    github_auth)    echo "authorize the installer's printed public key at GitHub -> Settings -> SSH and GPG keys -> New SSH key, then re-check" ;;
    *)              echo "" ;;
  esac
}

recheck() {
  case "$1" in
    apt) command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1 && dpkg -s git curl make sudo dnsmasq ufw jq apache2-utils sqlite3 python3-yaml >/dev/null 2>&1 ;;
    goose) command -v goose >/dev/null 2>&1 || [ -x /usr/local/bin/goose ] ;;
    user) id -u "root" >/dev/null 2>&1 ;;
    ssh_keys) [ -s /root/.ssh/authorized_keys ] ;;
    github_key) [ -s /root/.ssh/github_key ] ;;
    github_auth) github_auth_ok && github_push ;;
    render) bash "$REPO/scripts/render/render-all.sh" >/dev/null 2>&1 ;;
    tailscale) command -v tailscale >/dev/null 2>&1 ;;
    tailscale_up) tailscale ip -4 >/dev/null 2>&1 ;;
    ts_ip) [ -n "$(tailscale ip -4 2>/dev/null | head -1)" ] ;;
    install_config) systemctl is-active --quiet ttyd dnsmasq goose ;;
    fail2ban) systemctl is-active --quiet fail2ban && fail2ban-client status sshd >/dev/null 2>&1 ;;
    caddy) docker ps --format '{{.Names}}' | grep -qx caddy ;;
    nextcloud) docker ps --format '{{.Names}}' | grep -qx nextcloud && docker ps --format '{{.Names}}' | grep -qx talk-hpb && docker ps --format '{{.Names}}' | grep -qx talk-relay ;;
    nextcloud_db) docker ps --format '{{.Names}}' | grep -qx postgresql ;;
    vaultwarden) docker ps --format '{{.Names}}' | grep -qx vaultwarden ;;
    kuma) docker ps --format '{{.Names}}' | grep -qx uptimekuma ;;
    mailserver) docker ps --format '{{.Names}}' | grep -qx mailserver && docker ps --format '{{.Names}}' | grep -qx roundcube ;;
    datadirectory) if docker exec -w /var/www/html nextcloud php occ status 2>/dev/null | grep -q "installed: true"; then [ "$(docker exec -w /var/www/html nextcloud php occ config:system:get datadirectory 2>/dev/null | tr -d '\n')" = "/data" ]; else true; fi ;;
    kuma_admin) [ "$(docker exec uptimekuma sqlite3 /app/data/kuma.db "SELECT COUNT(*) FROM user WHERE username='admin';" 2>/dev/null | tr -d '\n')" = "1" ] ;;
    kuma_seed) [ "$(docker exec uptimekuma sqlite3 /app/data/kuma.db "SELECT COUNT(*) FROM monitor;" 2>/dev/null | tr -d '\n')" -gt 0 ] ;;
    zone) [ -n "$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" | jq -r '.result[0].id // empty')" ] ;;
    dns_*) local h=${1#dns_}; [ -n "$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=A&name=$h.$DOMAIN" | jq -r '.result[0].id // empty')" ] ;;
    cert_*) local h=${1#cert_}; echo | timeout 10 openssl s_client -connect 127.0.0.1:443 -servername "$h.$DOMAIN" 2>/dev/null | openssl x509 -noout -issuer 2>/dev/null | grep -q "Let's Encrypt" ;;
    sweep) [ -z "$(sweep_hits)" ] ;;
    sslmode) ssl_mode_full ;;
    nextcloud_setup) docker exec -u www-data nextcloud php occ config:system:get mail_smtphost 2>/dev/null | grep -q "mail.$DOMAIN" && docker exec -u www-data nextcloud php occ talk:signaling:list 2>/dev/null | grep -q "https://talk.$DOMAIN/signaling" && docker exec -u www-data nextcloud php occ talk:turn:list 2>/dev/null | grep -q "talk.$DOMAIN:3478" && docker exec -u www-data nextcloud php occ config:system:get trusted_domains 2>/dev/null | grep -qx "cloud.$DOMAIN" ;;
    dkim_setup)      dig +short TXT "mail._domainkey.$DOMAIN" @"$(dig +short NS "$DOMAIN" | head -1)" 2>/dev/null | grep -qE 'p=[A-Za-z0-9+/=]{100,}' ;;
    vaultwarden_setup) docker exec mailserver setup email list 2>/dev/null | grep -qiE "^[* ] *vaultwarden@$DOMAIN( |\$|\[)" ;;
    *) false ;;
  esac
}

is_expected() {
  case "$1" in
    zone|clone|sslmode|github_auth) return 0 ;;  # input prerequisites / dashboard steps the script can't do
    *) return 1 ;;
  esac
}

resolve_errors() {
  local remaining=("${ERR_TAGS[@]}")
  while [ ${#remaining[@]} -gt 0 ]; do
    echo ""
    local exp=() unexp=()
    for tag in "${remaining[@]}"; do
      if is_expected "$tag"; then exp+=("$tag"); else unexp+=("$tag"); fi
    done
    if [ ${#exp[@]} -gt 0 ]; then
      echo " Manual steps (expected):"
      for i in "${!exp[@]}"; do
        echo "   $((i+1)). ${exp[$i]}"
        echo "      problem: $(problem "${exp[$i]}")${ERR_DETAIL[${exp[$i]}]:+ (${ERR_DETAIL[${exp[$i]}]})}"
        echo "      hint: $(hint "${exp[$i]}")"
      done
    fi
    if [ ${#unexp[@]} -gt 0 ]; then
      echo " Unexpected errors (${#unexp[@]}):"
      for i in "${!unexp[@]}"; do
        echo "   $((i+1)). ${unexp[$i]}"
        echo "      problem: $(problem "${unexp[$i]}")${ERR_DETAIL[${unexp[$i]}]:+ (${ERR_DETAIL[${unexp[$i]}]})}"
        echo "      hint: $(hint "${unexp[$i]}")"
      done
    fi
    read -rp "Fix / complete the items above, then press Enter to re-check (Ctrl-C aborts): " input \
      || { echo "No terminal input — aborting."; exit 1; }
    local still=()
    for tag in "${remaining[@]}"; do
      if recheck "$tag"; then
        echo "   ✓ solved: $tag — $(problem "$tag")"
      else
        still+=("$tag")
      fi
    done
    remaining=("${still[@]}")
  done
  ERR_TAGS=()
  write_modules_conf
  finalize_hardening
  success_block
  ask_optimize
}

# ── Optional follow-up — only ever reached after a FULLY green run ────────
# optimize.sh is a separate tool (the VPS performance pass), so it is offered,
# never assumed. It is idempotent — re-running it is a no-op — which is why a
# re-run of install.sh may offer it again.
ask_optimize() {
  local answer rc
  [ -f "$REPO/scripts/ops/optimize.sh" ] || return 0
  while :; do
    read -rp "Also run the VPS performance pass (kernel, swap, disk tuning) now? (yes/no): " answer || return 0
    case "${answer,,}" in
      yes|y|true)  break ;;
      no|n|false)  log "  optimize.sh skipped — run it later: bash $REPO/scripts/ops/optimize.sh"; return 0 ;;
      *)           echo "   answer yes or no." ;;
    esac
  done
  log "  running scripts/ops/optimize.sh --yes (its output goes to $LOG)"
  bash "$REPO/scripts/ops/optimize.sh" --yes 2>&1 | tee -a "$LOG"
  rc=${PIPESTATUS[0]}
  if [ "$rc" = 0 ]; then
    log "  optimize.sh done"
  else
    log "  optimize.sh exited $rc — it is optional and can be re-run any time: bash $REPO/scripts/ops/optimize.sh"
  fi
}

finalize_hardening() {
  # Runs once every error is resolved: if a key exists now, harden sshd
  # (phase 1 skipped it when no key was present at install time).
  if [ -s /root/.ssh/authorized_keys ]; then
    printf 'PasswordAuthentication no\nPermitRootLogin prohibit-password\nAllowUsers root\n' \
      > /etc/ssh/sshd_config.d/50-cloud-init.conf
    chmod 600 /etc/ssh/sshd_config.d/50-cloud-init.conf
    systemctl restart sshd >/dev/null 2>&1 || true
  fi
  # Close the temporary installer-session SSH rule (tailnet access stays).
  local ip="${INSTALLER_SSH_IP:-}"
  if [ -n "$ip" ] && [ "$ip" != "$(tailscale ip -4 2>/dev/null | head -1)" ]; then
    ufw --force delete allow from "$ip" to any port 22 proto tcp >/dev/null 2>&1 || true
    ufw delete allow from "$ip" to any port 22 proto tcp >/dev/null 2>&1 || true
    log "  removed the temporary installer SSH allow for $ip (root@$NODE_NAME over the tailnet remains the entry point)"
  fi
}

success_block() {
  echo ""
  echo "=============================================================="
  echo " SUCCESS — the stack is up:"
  echo "   Nextcloud    https://cloud.$DOMAIN      admin / ${NEXTCLOUD_ADMIN_PASSWORD:-<see modules/nextcloud/.env>}"
  echo "   Vaultwarden  https://vault.$DOMAIN"
  echo "   Uptime Kuma  https://kuma.$DOMAIN       admin / ${KUMA_PASS:-(already set — rotate with: make kuma-passwd USER=admin PASS=…)}"
  echo "   Webmail      https://mail.$DOMAIN       (mailboxes via make mail-gen)"
  echo "   Shell        https://tail.$DOMAIN      (tailnet-only)"
  echo "   VPS IP ${VPS_IP:-?}   Tailscale IP ${TS_IP:-?}"
  echo ""
  echo " SSH: root@$NODE_NAME is the only entry point (key-only, tailnet-only, port 22)."
  echo ""
  echo " ── SSH ACCESS ───────────────────────────────────────────────────────────"
  if [ -s /root/.ssh/authorized_keys ]; then
    echo "  Hardening IS applied: $(grep -c . /root/.ssh/authorized_keys) key(s) authorized,"
    echo "  password auth off, root key-only. Re-run the installer to add another."
  else
    echo "  WARNING: no key in /root/.ssh/authorized_keys, so hardening is NOT applied"
    echo "  (password auth stays on). Re-run the installer and paste your device's pubkey."
  fi
  echo " ─────────────────────────────────────────────────────────────────────────"
  echo ""
  echo " Follow-ups (none block the install):"
  echo "   1. Tailscale split-DNS: admin console -> DNS -> add $DOMAIN -> ${TS_IP:-<tailscale IP>}"
  echo "      so tail.$DOMAIN resolves for tailnet devices (dnsmasq on the VPS already answers it)"
  echo "   2. (optional) Cloudflare WAF rule skip for cloud.$DOMAIN (desktop sync)"
  if [ "${GH_REMOTE:-false}" = "true" ]; then
    echo "   3. GitHub remote access: origin is git@github.com:$GITHUB_USER/$REPO_NAME.git, key /root/.ssh/github_key"
  else
    echo "   3. No GitHub remote access (declined at the last prompt) — re-run the installer and answer true to mint the push key"
  fi
  echo "   4. Mailboxes: make mail-gen MAIL=name@$DOMAIN (or bare make mail-gen for a disposable);"
  echo "      the nextcloud@$DOMAIN SMTP sender mailbox is created automatically"
  echo "=============================================================="
}

summary() {
  if [ ${#ERR_TAGS[@]} -gt 0 ]; then
    echo ""
    echo " ERROR(S) — no success until every item below is resolved:"
    local exp=() unexp=()
    for tag in "${ERR_TAGS[@]}"; do
      if is_expected "$tag"; then exp+=("$tag"); else unexp+=("$tag"); fi
    done
    if [ ${#exp[@]} -gt 0 ]; then
      echo " Manual steps (expected):"
      for i in "${!exp[@]}"; do
        echo "   $((i+1)). ${exp[$i]}"
        echo "      problem: $(problem "${exp[$i]}")${ERR_DETAIL[${exp[$i]}]:+ (${ERR_DETAIL[${exp[$i]}]})}"
        echo "      hint: $(hint "${exp[$i]}")"
      done
    fi
    if [ ${#unexp[@]} -gt 0 ]; then
      echo " Unexpected errors (${#unexp[@]}):"
      for i in "${!unexp[@]}"; do
        echo "   $((i+1)). ${unexp[$i]}"
        echo "      problem: $(problem "${unexp[$i]}")${ERR_DETAIL[${unexp[$i]}]:+ (${ERR_DETAIL[${unexp[$i]}]})}"
        echo "      hint: $(hint "${unexp[$i]}")"
      done
    fi
  fi
}
trap summary EXIT

# ─────────────────────────────── main ──────────────────────────────────────

# A previous, incomplete run leaves either the saved answers (setup.state) or the
# instance.conf a run writes once the prompts are answered.
previous_install() { [ -s "${STATE:-}" ] || [ -s "$DATA/instance.conf" ]; }

main() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root: root@$NODE_NAME is the only entry point (no sudo hand-off)."; exit 1
  fi
  ensure_runtime_dirs       # first: the prompts below log (see the helper)
  banner
  load_state
  if previous_install; then
    echo ""
    echo "A previous installation was detected."
    read -rp "Do you want to resume the previous installation? [Y/n]: " _resume || _resume=""
    case "${_resume,,}" in
      n|no)
        echo "Starting fresh — every prompt will be asked again (saved answers dropped)."
        unset DOMAIN CF_API_TOKEN TS_AUTHKEY TS_IP \
              MOD_CLOUD MOD_VAULT MOD_MAIL MOD_MONITOR GH_REMOTE
        rm -f "$STATE" "$DATA/instance.conf"
        ;;
      *)
        echo "Resuming — only values that are still missing get asked."
        ;;
    esac
  else
    # No previous run: drop whatever instance.sh's fallbacks put in the
    # environment (notably DOMAIN=example.com) so no prompt is silently skipped.
    unset DOMAIN CF_API_TOKEN TS_AUTHKEY
  fi
  ask_inputs
  save_state

  github_access
  write_instance_conf
  phase_host
  phase_stack
  resolve_errors
}

main "$@"
# Cloudflare DNS records for fxmq.net
# CNAME root to www
cf_dns_create_or_update "@" "CNAME" "www.fxmq.net"
# SPF
cf_dns_create_or_update "@" "TXT" "v=spf1 -all"
# DKIM placeholder
cf_dns_create_or_update "*._domainkey" "TXT" "v=DKIM1; p="
# DMARC
cf_dns_create_or_update "_dmarc" "TXT" "v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s;"


# Execute split phase scripts sequentially
for f in "$(dirname "$0")/phases/phase_*.sh"; do
  [ -x "$f" ] && . "$f" || { echo "Failed $f"; exit 1; }
done

