#!/usr/bin/env bash
# scripts/render/render-all.sh — skeleton + data/instance.conf → data/rendered/.
#
# Two outputs, from one source of values:
#
#   1. data/rendered/caddy/   the edge tree (Caddyfile, vhosts/, www/) with
#                             every {{TOKEN}} replaced. The edge container
#                             mounts THIS, never the repo, so the checkout
#                             can stay a pure skeleton.
#   2. data/rendered/config/  every file under config/ rendered the same way
#                             (systemd units, dnsmasq, cron, logrotate, the
#                             shell banner, sysctl). `make install-config`
#                             copies from here.
#
# It also refreshes the marked instance block in each modules/*/.env, which is
# how the COMPOSE files get ${DOMAIN} / ${REPO_DIR} / ${DATA_DIR} without the
# repo containing a single real value. Compose reads the .env next to the
# compose file (that is already how the per-service secrets work) — the block
# is replaced, never appended twice, and the secrets above it are untouched.
#
# Idempotent. Run by `make render`, by `make install-config` and by
# scripts/stack/stack-up.sh before it touches the edge.
set -uo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"
CONF="$ROOT/data/instance.conf"
OUT="$ROOT/data/rendered"
RENDER="$ROOT/scripts/render/render.sh"

[ -f "$CONF" ] || { echo "render-all: missing $CONF (see config/instance.defaults)" >&2; exit 1; }

val() { sed -n "s/^$1=//p" "$CONF" | head -1; }
DATA_DIR="$(val DATA_DIR)"; [ -n "$DATA_DIR" ] || DATA_DIR="$ROOT/data"

# NEVER rm -rf $OUT: data/rendered/caddy is bind-mounted into the running edge,
# and deleting the directory deletes the inode the container holds. Caddy keeps
# serving its already-loaded config but every static file 404s (/welcome,
# /download, the operator's pages) until the container is recreated — which is exactly what
# happened on 2026-09-22. Render into a scratch tree and rsync it in place:
# rsync writes files into the EXISTING directory and deletes only stale files.
TMP="$(dirname "$OUT")/.render-tmp.$$"
rm -rf "$TMP"; mkdir -p "$TMP/caddy" "$TMP/config"

render_tree() {   # render_tree <src-dir> <dest-dir> [exclude-name]
  local src="$1" dst="$2" skip="${3:-}" rel
  ( cd "$src" && find . -type f ) | sed 's|^\./||' | while IFS= read -r rel; do
    [ "$rel" = "$skip" ] && continue
    mkdir -p "$dst/$(dirname "$rel")"
    chmod 0755 "$dst" "$dst/$(dirname "$rel")" 2>/dev/null || true
    "$RENDER" "$src/$rel" "$dst/$rel" || exit 1
  done
}

render_tree "$ROOT/modules/caddy" "$TMP/caddy" Dockerfile
render_tree "$ROOT/config" "$TMP/config" instance.defaults www
# (skip www: config/www holds TEMPLATE web pages, not host config — they belong
#  in the web root, rendered below, not under /etc)

# Swap in place (keeps the mounted inode alive), then drop the scratch tree.
mkdir -p "$OUT/caddy" "$OUT/config"
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete "$TMP/caddy/"  "$OUT/caddy/"
  rsync -a --delete "$TMP/config/" "$OUT/config/"
else
  # Fallback: copy over, then remove files whose source is gone. Never rm -rf.
  cp -a "$TMP/." "$OUT/"
  ( cd "$TMP" && find . -type f ) | sed 's|^\./||' > "$TMP/.list"
  ( cd "$OUT" && find . -type f ) | sed 's|^\./||' | while IFS= read -r f; do
      grep -qxF "$f" "$TMP/.list" || rm -f "$OUT/$f"
    done
fi
rm -rf "$TMP"

# Web root ($DATA/www): the TEMPLATE pages from config/www are rendered
# straight into it. Operator pages in there are never touched (nothing is
# deleted) — only the template files are (re)written, because they are part of
# the access layer, not content. Today that is the tail door list.
mkdir -p "$DATA_DIR/www"
render_tree "$ROOT/config/www" "$DATA_DIR/www"

# ── instance block for compose ──────────────────────────────────────────────
block() {
  echo "# >>> instance values (generated by 'make render' from data/instance.conf — do not edit)"
  for k in DOMAIN HOSTNAME OPERATOR GITHUB_USER REPO_NAME REPO_DIR DATA_DIR SERVER_IP EMAIL TIMEZONE; do
    printf '%s=%s\n' "$k" "$(val "$k")"
  done
  echo "# <<< instance values"
}

for d in "$ROOT"/modules/*/; do
  [ -f "$d/docker-compose.yml" ] || continue
  envf="$d/.env"
  if [ -f "$envf" ]; then
    sed -i '/^# >>> instance values/,/^# <<< instance values/d' "$envf"
    # collapse a possible double blank line the delete can leave behind
    sed -i '/^$/N;/^\n$/D' "$envf"
  else
    : > "$envf"
  fi
  block >> "$envf"
  chmod 600 "$envf"
done

echo "info:  rendered $(find "$OUT" -type f | wc -l) file(s) into $OUT"
echo "info:  refreshed the instance block in $(ls -d "$ROOT"/modules/*/.env 2>/dev/null | wc -l) service .env file(s)"
