#!/usr/bin/env bash
# scripts/render-all.sh — skeleton + data/instance.conf → data/rendered/.
#
# Two outputs, from one source of values:
#
#   1. data/rendered/caddy/   the edge tree (Caddyfile, vhosts/, www/) with
#                             every {{TOKEN}} replaced. The edge container
#                             mounts THIS, never the repo, so the checkout
#                             can stay a pure skeleton.
#   2. data/rendered/config/  every file under config/ rendered the same way
#                             (systemd units, dnsmasq, cron, logrotate, the
#                             shell banner, sysctl). `make install-config`
#                             copies from here.
#
# It also refreshes the marked instance block in each services/*/.env, which is
# how the COMPOSE files get ${DOMAIN} / ${REPO_DIR} / ${DATA_DIR} without the
# repo containing a single real value. Compose reads the .env next to the
# compose file (that is already how the per-service secrets work) — the block
# is replaced, never appended twice, and the secrets above it are untouched.
#
# Idempotent. Run by `make render`, by `make install-config` and by
# scripts/stack-up.sh before it touches the edge.
set -uo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
CONF="$ROOT/data/instance.conf"
OUT="$ROOT/data/rendered"
RENDER="$ROOT/scripts/render.sh"

[ -f "$CONF" ] || { echo "render-all: missing $CONF (see config/instance.defaults)" >&2; exit 1; }

val() { sed -n "s/^$1=//p" "$CONF" | head -1; }

rm -rf "$OUT"
mkdir -p "$OUT/caddy" "$OUT/config"

render_tree() {   # render_tree <src-dir> <dest-dir> [exclude-name]
  local src="$1" dst="$2" skip="${3:-}" rel
  ( cd "$src" && find . -type f ) | sed 's|^\./||' | while IFS= read -r rel; do
    [ "$rel" = "$skip" ] && continue
    mkdir -p "$dst/$(dirname "$rel")"
    chmod 0755 "$dst" "$dst/$(dirname "$rel")" 2>/dev/null || true
    "$RENDER" "$src/$rel" "$dst/$rel" || exit 1
  done
}

render_tree "$ROOT/services/caddy" "$OUT/caddy" Dockerfile
render_tree "$ROOT/config" "$OUT/config" instance.defaults   # docs, not a template to install

# ── instance block for compose ──────────────────────────────────────────────
block() {
  echo "# >>> instance values (generated by 'make render' from data/instance.conf — do not edit)"
  for k in DOMAIN HOSTNAME OPERATOR GITHUB_USER REPO_NAME REPO_DIR DATA_DIR SERVER_IP EMAIL TIMEZONE; do
    printf '%s=%s\n' "$k" "$(val "$k")"
  done
  echo "# <<< instance values"
}

for d in "$ROOT"/services/*/; do
  [ -f "$d/docker-compose.yml" ] || continue
  envf="$d/.env"
  if [ -f "$envf" ]; then
    sed -i '/^# >>> instance values/,/^# <<< instance values/d' "$envf"
    # collapse a possible double blank line the delete can leave behind
    sed -i '/^$/N;/^\n$/D' "$envf"
  else
    : > "$envf"
  fi
  block >> "$envf"
  chmod 600 "$envf"
done
# the kefoMC unit lives in another repo, but it also joins `net`: give it the
# values too so nothing has to be hand-edited there after a rename.
if [ -d /root/github/kefoMC ]; then
  : >> /root/github/kefoMC/.env
  sed -i '/^# >>> instance values/,/^# <<< instance values/d' /root/github/kefoMC/.env 2>/dev/null || true
  { block; } >> /root/github/kefoMC/.env 2>/dev/null || true
fi

echo "info:  rendered $(find "$OUT" -type f | wc -l) file(s) into $OUT"
echo "info:  refreshed the instance block in $(ls -d "$ROOT"/services/*/.env 2>/dev/null | wc -l) service .env file(s)"
